In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets
import seaborn as sns
TRAIN_DATASET_PATH = 'train.csv'
TEST_DATASET_PATH = 'test.csv'

In [2]:
np.random.seed(1234)

In [3]:
df = pd.read_csv(TRAIN_DATASET_PATH)
display(df.head())
print(df.shape)

Id   age  years_of_experience  lesson_price  qualification  physics  \
0   0  40.0                  0.0        1400.0            1.0      1.0   
1   1  48.0                  4.0        2850.0            3.0      1.0   
2   2  39.0                  0.0        1200.0            1.0      0.0   
3   3  46.0                  5.0        1400.0            1.0      0.0   
4   4  43.0                  1.0        1500.0            1.0      0.0   

   chemistry  biology  english  geography  history  mean_exam_points  
0        0.0      0.0      0.0        1.0      0.0              63.0  
1        0.0      0.0      0.0        0.0      0.0              86.0  
2        0.0      0.0      0.0        0.0      0.0              53.0  
3        0.0      0.0      0.0        0.0      0.0              56.0  
4        0.0      0.0      0.0        0.0      0.0              59.0

(10000, 12)


In [4]:
test = pd.read_csv(TEST_DATASET_PATH)
print(test.shape)

(10000, 11)


In [5]:
TARGET_NAME = 'mean_exam_points'
FEATURE_NAMES = ['age', 'years_of_experience', 'lesson_price', 'qualification',
       'physics', 'chemistry', 'biology', 'english', 'geography', 'history']

In [6]:
X = df[FEATURE_NAMES].values
Y = df[TARGET_NAME].values

print(X.shape, Y.shape)

(10000, 10) (10000,)


In [7]:
# Возьмем 10 признаков и 10000 объектов
n_features = 10
n_objects = 10000

# сгенерируем вектор истинных весов
#w_true = np.random.normal(size=(n_features, ))

# сгенерируем матрицу X, вычислим Y с добавлением случайного шума
#X = np.random.uniform(-7, 7, (n_objects, n_features))
#Y = X.dot(w_true) + np.random.normal(0, 0.5, size=(n_objects))

# возьмем нулевые начальные веса
w = np.zeros(n_features)
w

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# реализуем функцию, определяющую среднеквадратичную ошибку
def mserror(X, w, y_pred):
    y = X.dot(w)
    return (sum((y - y_pred)**2)) / len(y)
def calc_mse(y, y_pred):
  err = np.mean((y - y_pred)**2)
  return err

In [9]:
def normal_equation(X, y):
    return np.linalg.solve((X.T).dot(X), (X.T).dot(y))

normal_eq_w = normal_equation(X, Y)
print(f'В случае использования нормального уравнения функционал ошибки составляет {round(mserror(X, normal_eq_w, Y), 4)}')

В случае использования нормального уравнения функционал ошибки составляет 88.8027


In [10]:
normal_eq_w

array([0.50924797, 0.19438164, 0.01427329, 7.35715911, 6.36555615,
       1.26278512, 2.1159237 , 2.31825251, 1.06574434, 0.54044291])

In [11]:
X_test = test[FEATURE_NAMES].values

In [12]:
#Y_predict = X_test.dot(normal_eq_w)
#submissions = pd.concat([test['Id'], pd.Series(Y_predict)], axis=1)
#submissions = submissions.rename(columns={0: 'mean_exam_points'})
#submissions.to_csv('Kalmina_1.csv',index=None)

In [13]:
from sklearn import linear_model

# создадим модель
linear_regressor = linear_model.LinearRegression(normalize=True)

# обучим ее
linear_regressor.fit(X, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [14]:
# выведем полученный вес при признаке и свободный коэффициент
print(linear_regressor.coef_, linear_regressor.intercept_)

[-0.0127303   0.21323088  0.00847091  8.37242534  5.18804248  0.53017841
  1.21269343  1.20929819  0.75465894  0.13378621] 33.471192515282965


In [15]:
hm = linear_regressor.predict(X)
print(calc_mse(hm, Y))

64.27270386649735


In [16]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

# создадим новую кубическую модель
third_degree_regressor = make_pipeline(PolynomialFeatures(degree=2), linear_model.LinearRegression(normalize=True))

# обучим ее
third_degree_regressor.fit(X, Y)

Pipeline(memory=None,
         steps=[('polynomialfeatures',
                 PolynomialFeatures(degree=2, include_bias=True,
                                    interaction_only=False, order='C')),
                ('linearregression',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=True))],
         verbose=False)

In [17]:
#third_degree_regressor.predict(X)

In [18]:
#hm2 = third_degree_regressor.predict(X)
#print(calc_mse(hm2, Y))

In [19]:
#y_pred = third_degree_regressor.predict(X_test)

In [20]:
#submissions = pd.concat([test['Id'], pd.Series(y_pred)], axis=1)

In [21]:
#submissions = submissions.rename(columns={0: 'mean_exam_points'})

In [22]:
#submissions.to_csv('Kalmina_5.csv',index=None)

In [23]:
df['inter']=1

In [24]:
df

Id   age  years_of_experience  lesson_price  qualification  physics  \
0        0  40.0                  0.0        1400.0            1.0      1.0   
1        1  48.0                  4.0        2850.0            3.0      1.0   
2        2  39.0                  0.0        1200.0            1.0      0.0   
3        3  46.0                  5.0        1400.0            1.0      0.0   
4        4  43.0                  1.0        1500.0            1.0      0.0   
...    ...   ...                  ...           ...            ...      ...   
9995  9995  44.0                  0.0        1700.0            2.0      1.0   
9996  9996  51.0                  0.0        1700.0            2.0      0.0   
9997  9997  34.0                  1.0        1250.0            1.0      1.0   
9998  9998  33.0                  3.0        1100.0            1.0      0.0   
9999  9999  35.0                  0.0        1450.0            1.0      0.0   

      chemistry  biology  english  geography  history  mean_exam_points  inter  
0           0.0      0.0      0.0        1.0      0.0              63.0      1  
1           0.0      0.0      0.0        0.0      0.0              86.0      1  
2           0.0      0.0      0.0        0.0      0.0              53.0      1  
3           0.0      0.0      0.0        0.0      0.0              56.0      1  
4           0.0      0.0      0.0        0.0      0.0              59.0      1  
...         ...      ...      ...        ...      ...               ...    ...  
9995        1.0      0.0      0.0        0.0      0.0              78.0      1  
9996        0.0      0.0      0.0        0.0      0.0              64.0      1  
9997        0.0      0.0      0.0        0.0      0.0              58.0      1  
9998        0.0      0.0      0.0        0.0      0.0              51.0      1  
9999        0.0      0.0      0.0        0.0      0.0              59.0      1  

[10000 rows x 13 columns]

In [25]:
FEATURE_NAMES = ['inter', 'age', 'years_of_experience', 'lesson_price', 'qualification',
       'physics', 'chemistry', 'biology', 'english', 'geography', 'history']
X = df[FEATURE_NAMES].values

In [26]:
X=X.T
X

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [40., 48., 39., ..., 34., 33., 35.],
       [ 0.,  4.,  0., ...,  1.,  3.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [27]:
X_norm = X.copy()
X_norm = X_norm.astype(np.float64)
for p in [1,2,3,4]:
    X_norm[p] = (X[p] - X[p].min()) / (X[p].max() - X[p].min())
X_norm

array([[1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.37777778, 0.55555556, 0.35555556, ..., 0.24444444, 0.22222222,
        0.26666667],
       [0.        , 0.4       , 0.        , ..., 0.1       , 0.3       ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [28]:
def calc_std_feat(x):
  res = (x - x.mean()) / x.std()
  return res

X_st = X.copy().astype(np.float64)
for s in [1,2,3,4]:
    X_st[s] = calc_std_feat(X[s])
X_st

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [-0.73077401,  0.26381464, -0.85509759, ..., -1.4767155 ,
        -1.60103908, -1.35239192],
       [-1.1211401 ,  1.13603747, -1.1211401 , ..., -0.55684571,
         0.57174308, -1.1211401 ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [29]:
def eval_model(X, y, iterations, alpha=3e-2):
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    err_min = 10000
    W_min = []
    for i in range(1, iterations+1):
        y_pred = np.dot(W, X)
        err = calc_mse(y, y_pred)
        W -= (alpha * (1/n * 2 * np.dot((y_pred - y), X.T)))
        if err < err_min:
            err_min = err
            W_min.append(W)
        if i % (iterations / 100) == 0:
            print(i, W, err)
    return W_min, err_min

w = np.zeros(11)
w_list = [w.copy()]
errors = []
# шаг градиентного спуска
eta = 0.000003
max_iter = 1e6
# критерий сходимости (разница весов, при которой алгоритм останавливается)
min_weight_dist = 1e-10
# зададим начальную разницу весов большим числом
weight_dist = np.inf
iter_num = 0
# ход градиентного спуска
new_w = np.random.randn(X.shape[0])
n = X_st.shape[1]
while weight_dist > min_weight_dist and iter_num < max_iter:
    # генерируем случайный индекс объекта выборки
    train_ind = np.random.randint(X_st.shape[0])
    y_pred = np.dot(w, X_st)
    new_w -= (eta * (1/n * 2 * np.dot((y_pred - Y), X_st.T)))
    weight_dist = np.linalg.norm(new_w - w, ord=2) 
    w_list.append(new_w.copy())
    errors.append(mserror(X_st.T, new_w, Y))   
    iter_num += 1
    w = new_w
    print({mserror(X_st.T, new_w, Y)})
    
    
w_list = np.array(w_list)

print(f'В случае использования стохастического градиентного спуска функционал ошибки составляет {round(errors[-1], 4)}')

In [30]:
#w_pred, err_pred = eval_model(X_st, Y, iterations=10000, alpha=3e-2)
#print(w_pred, err_pred)

In [31]:
test['inter']=1
X_test = test[FEATURE_NAMES].values
X_test=X_test.T
X_test

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [46., 43., 52., ..., 33., 48., 49.],
       [ 3.,  3.,  1., ...,  5.,  0.,  5.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [32]:
X_test_st = X_test.copy().astype(np.float64)
for s in [1,2,3,4]:
    X_test_st[s] = calc_std_feat(X_test[s])
X_test_st

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 0.00341885, -0.37366064,  0.75757784, ..., -1.63059229,
         0.25480518,  0.38049835],
       [ 0.57200559,  0.57200559, -0.54957399, ...,  1.69358516,
        -1.11036378,  1.69358516],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [33]:
X_test_st = X_test_st.T
#Y_predict_3 = X_test_st.dot(w_pred)

In [34]:
def eval_sgd_model(X, y, iterations, qty_in_batch, alpha=1e-4):
  W = np.random.randn(X.shape[0])
  n = X.shape[1]
  n_batch = n // qty_in_batch
  if n % qty_in_batch != 0:
    n_batch += 1
  for i in range(1, iterations+1):
    for b in range(n_batch):
      start_ = qty_in_batch*b
      end_ = qty_in_batch*(b+1)
      
      # print(b, n_batch, start_, end_)
      
      X_tmp = X[:, start_ : end_]
      y_tmp = y[start_ : end_]
      y_pred_tmp = np.dot(W, X_tmp)
      err = calc_mse(y_tmp, y_pred_tmp)
      W -= (alpha * (1/n * 2 * np.dot((y_pred_tmp - y_tmp), X_tmp.T)))
    if i % (iterations / 10) == 0:
      print(i, W, err)
  return W

In [35]:
#w_pred_2 = eval_sgd_model(X_st, Y, iterations=2000, qty_in_batch=5, alpha=1e-2)
#w_pred_2

In [36]:
def eval_model_reg2(X, y, iterations, alpha=1e-4, lambda_=1e-8):
  np.random.seed(42)
  W = np.random.randn(X.shape[0])
  n = X.shape[1]
  for i in range(1, iterations+1):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    W -= alpha * (1/n * 2 * np.dot((y_pred - y), X.T) + lambda_ * W) 
    if i % (iterations / 10) == 0:
      print(i, W, err)
  return W

In [43]:
reg2 = eval_model_reg2(X_st, Y, iterations=500000, alpha=1e-3, lambda_=1e-8)
reg2

50000 [62.09432037 -0.10271562  0.37789697  4.44559371  6.63323788  5.18810656
  0.53110678  1.21371725  1.2221505   0.845035    0.22683225] 64.27312759398316
100000 [62.0997193  -0.10242538  0.37784557  4.44601882  6.63287603  5.18803445
  0.53026183  1.21266587  1.20950984  0.7588464   0.1478218 ] 64.27270814343436
150000 [62.10010339 -0.10239977  0.37786653  4.44604413  6.632845    5.18804115
  0.53018926  1.21268439  1.2093126   0.75486389  0.13589074] 64.27270395190533
200000 [62.10014567 -0.10239692  0.37787086  4.44604597  6.63284148  5.18804259
  0.53018022  1.21269208  1.20930011  0.75467078  0.13410144] 64.27270386839032
250000 [62.10015133 -0.10239654  0.37787157  4.44604616  6.632841    5.18804282
  0.53017895  1.21269345  1.20929863  0.75466004  0.1338336 ] 64.27270386654025
300000 [62.10015215 -0.10239649  0.37787167  4.44604618  6.63284093  5.18804286
  0.53017877  1.21269367  1.20929842  0.75465925  0.13379353] 64.27270386649855
350000 [62.10015227 -0.10239648  0.377871

array([62.10015229, -0.10239648,  0.37787169,  4.44604618,  6.63284092,
        5.18804286,  0.53017873,  1.21269371,  1.20929839,  0.75465915,
        0.13378649])

In [38]:
#Y_predict_4 = X_test_st.dot(reg2)
#submissions = pd.concat([test['Id'], pd.Series(Y_predict_4)], axis=1)
#submissions = submissions.rename(columns={0: 'mean_exam_points'})
#submissions.to_csv('Kalmina_reg2.csv',index=None)

In [45]:
def eval_model_reg1(X, y, iterations, alpha=1e-4, lambda_=1e-8):
  np.random.seed(42)
  W = np.random.randn(X.shape[0])
  n = X.shape[1]
  for i in range(1, iterations+1):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    W -= alpha * (1/n * 2 * np.dot((y_pred - y), X.T) + lambda_ * np.sign(W)) 
    if i % (iterations / 10) == 0:
      print(i, W, err)
  return W

In [46]:
reg1 = eval_model_reg1(X_st, Y, iterations=500000, alpha=1e-3, lambda_=1e-8)
reg1

50000 [62.09432094 -0.10271561  0.37789696  4.4455937   6.63323792  5.18810616
  0.53110642  1.21371693  1.22215022  0.84503469  0.22683185] 64.27312759024514
100000 [62.09971987 -0.10242537  0.37784556  4.44601881  6.63287607  5.18803406
  0.53026147  1.21266555  1.20950954  0.75884604  0.14782129] 64.27270814305378
150000 [62.10010397 -0.10239976  0.37786652  4.44604411  6.63284504  5.18804075
  0.5301889   1.21268406  1.20931231  0.75486352  0.13589021] 64.27270395185703
200000 [62.10014625 -0.10239692  0.37787086  4.44604595  6.63284152  5.18804219
  0.53017986  1.21269175  1.20929982  0.75467041  0.13410091] 64.27270386838339
250000 [62.10015191 -0.10239653  0.37787156  4.44604614  6.63284104  5.18804243
  0.53017859  1.21269313  1.20929834  0.75465967  0.13383307] 64.27270386653913
300000 [62.10015272 -0.10239648  0.37787167  4.44604616  6.63284097  5.18804246
  0.53017841  1.21269334  1.20929813  0.75465888  0.133793  ] 64.27270386649823
350000 [62.10015284 -0.10239647  0.377871

array([62.10015287, -0.10239647,  0.37787169,  4.44604617,  6.63284096,
        5.18804247,  0.53017837,  1.21269338,  1.2092981 ,  0.75465878,
        0.13378595])