Можно ли отобрать наиболее значимые признаки с помощью PCA?

---- Нет, он предназначен для снижения размерности, а не для отбора уже имеющихся.

2*. Примите участие в одном или двух соревнованиях и пришлите

свой псевдоним на Kaggle и ссылку на github с решением соревнования

по регрессии ()

------ JaneCalm

или классификации (https://www.kaggle.com/c/choose-tutors).

В скрипте можно использовать только эти импорты:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
import seaborn as sns
TRAIN_DATASET_PATH = 'train.csv'
TEST_DATASET_PATH = 'test.csv'

In [2]:
np.random.seed(42)

In [3]:
df = pd.read_csv(TRAIN_DATASET_PATH)
display(df.head())
print(df.shape)

Id   age  years_of_experience  lesson_price  qualification  physics  \
0   0  40.0                  0.0        1400.0            1.0      1.0   
1   1  48.0                  4.0        2850.0            3.0      1.0   
2   2  39.0                  0.0        1200.0            1.0      0.0   
3   3  46.0                  5.0        1400.0            1.0      0.0   
4   4  43.0                  1.0        1500.0            1.0      0.0   

   chemistry  biology  english  geography  history  mean_exam_points  
0        0.0      0.0      0.0        1.0      0.0              63.0  
1        0.0      0.0      0.0        0.0      0.0              86.0  
2        0.0      0.0      0.0        0.0      0.0              53.0  
3        0.0      0.0      0.0        0.0      0.0              56.0  
4        0.0      0.0      0.0        0.0      0.0              59.0

(10000, 12)


In [4]:
test = pd.read_csv(TEST_DATASET_PATH)

In [5]:
TARGET_NAME = 'mean_exam_points'
FEATURE_NAMES = ['age', 'years_of_experience', 'lesson_price', 'qualification',
       'physics', 'chemistry', 'biology', 'english', 'geography', 'history']

In [6]:
X = df[FEATURE_NAMES].values
Y = df[TARGET_NAME].values

In [7]:
# Возьмем 10 признаков и 10000 объектов
n_features = 10
n_objects = 10000

# сгенерируем вектор истинных весов
#w_true = np.random.normal(size=(n_features, ))

# сгенерируем матрицу X, вычислим Y с добавлением случайного шума
#X = np.random.uniform(-7, 7, (n_objects, n_features))
#Y = X.dot(w_true) + np.random.normal(0, 0.5, size=(n_objects))

# возьмем нулевые начальные веса
w = np.zeros(n_features)
w

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# реализуем функцию, определяющую среднеквадратичную ошибку
def mserror(X, w, y_pred):
    y = X.dot(w)
    return (sum((y - y_pred)**2)) / len(y)
def calc_mse(y, y_pred):
  err = np.mean((y - y_pred)**2)
  return err

In [9]:
def normal_equation(X, y):
    return np.linalg.solve((X.T).dot(X), (X.T).dot(y))

normal_eq_w = normal_equation(X, Y)
print(f'В случае использования нормального уравнения функционал ошибки составляет {round(mserror(X, normal_eq_w, Y), 4)}')

В случае использования нормального уравнения функционал ошибки составляет 88.8027


In [10]:
normal_eq_w

array([0.50924797, 0.19438164, 0.01427329, 7.35715911, 6.36555615,
       1.26278512, 2.1159237 , 2.31825251, 1.06574434, 0.54044291])

In [11]:
X_test = test[FEATURE_NAMES].values

In [12]:
#Y_predict = X_test.dot(normal_eq_w)
#submissions = pd.concat([test['Id'], pd.Series(Y_predict)], axis=1)
#submissions = submissions.rename(columns={0: 'mean_exam_points'})
#submissions.to_csv('Kalmina_1.csv',index=None)

In [13]:
#df['inter']=1

In [14]:
#FEATURE_NAMES = ['inter', 'age', 'years_of_experience', 'lesson_price', 'qualification',
#       'physics', 'chemistry', 'biology', 'english', 'geography', 'history']
#X = df[FEATURE_NAMES].values

In [15]:
#X=X.T
#X

In [16]:
X_norm = X.copy()
X_norm = X_norm.astype(np.float64)
for p in range(len(X_norm)):
    X_norm[p] = (X[p] - X[p].min()) / (X[p].max() - X[p].min())
X_norm

array([[2.85714286e-02, 0.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 7.14285714e-04, 0.00000000e+00],
       [1.68421053e-02, 1.40350877e-03, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.25000000e-02, 0.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [2.72000000e-02, 8.00000000e-04, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.00000000e-02, 2.72727273e-03, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.41379310e-02, 0.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [17]:
def calc_std_feat(x):
    res = (x - x.mean()) / x.std()
    return res

X_st = X.copy().astype(np.float64)
for s in range(len(X_st)):
    X_st[s] = calc_std_feat(X[s])
#X_st = X_st.T

In [18]:
def eval_model(X, y, iterations, alpha=3e-2):
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    err_min = 10000
    W_min = []
    for i in range(1, iterations+1):
        y_pred = np.dot(W, X)
        err = calc_mse(y, y_pred)
        W -= (alpha * (1/n * 2 * np.dot((y_pred - y), X.T)))
        if err < err_min:
            err_min = err
            W_min.append(W)
        if i % (iterations / 100) == 0:
            print(i, W, err)
    return W_min, err_min

w = np.zeros(11)
w_list = [w.copy()]
errors = []
# шаг градиентного спуска
eta = 0.000003
max_iter = 1e6
# критерий сходимости (разница весов, при которой алгоритм останавливается)
min_weight_dist = 1e-10
# зададим начальную разницу весов большим числом
weight_dist = np.inf
iter_num = 0
# ход градиентного спуска
new_w = np.random.randn(X.shape[0])
n = X_st.shape[1]
while weight_dist > min_weight_dist and iter_num < max_iter:
    # генерируем случайный индекс объекта выборки
    train_ind = np.random.randint(X_st.shape[0])
    y_pred = np.dot(w, X_st)
    new_w -= (eta * (1/n * 2 * np.dot((y_pred - Y), X_st.T)))
    weight_dist = np.linalg.norm(new_w - w, ord=2) 
    w_list.append(new_w.copy())
    errors.append(mserror(X_st.T, new_w, Y))   
    iter_num += 1
    w = new_w
    print({mserror(X_st.T, new_w, Y)})
    
    
w_list = np.array(w_list)

print(f'В случае использования стохастического градиентного спуска функционал ошибки составляет {round(errors[-1], 4)}')

In [19]:
#w_pred, err_pred = eval_model(X_st, Y, iterations=10000, alpha=3e-2)
#print(w_pred, err_pred)

In [20]:
#test['inter']=1
#X_test = test[FEATURE_NAMES].values
#X_test=X_test.T
#X_test

In [21]:
X_test_st = X_test.copy().astype(np.float64)
for s in range(len(X_test_st)):
    X_test_st[s] = calc_std_feat(X_test[s])
#X_test_st = X_test_st.T

In [22]:
#X_test_st = X_test_st.T
#Y_predict_3 = X_test_st.dot(w_pred)

In [23]:
def eval_sgd_model(X, y, iterations, qty_in_batch, alpha=1e-4):
  W = np.random.randn(X.shape[0])
  n = X.shape[1]
  n_batch = n // qty_in_batch
  if n % qty_in_batch != 0:
    n_batch += 1
  for i in range(1, iterations+1):
    for b in range(n_batch):
      start_ = qty_in_batch*b
      end_ = qty_in_batch*(b+1)
      
      # print(b, n_batch, start_, end_)
      
      X_tmp = X[:, start_ : end_]
      y_tmp = y[start_ : end_]
      y_pred_tmp = np.dot(W, X_tmp)
      err = calc_mse(y_tmp, y_pred_tmp)
      W -= (alpha * (1/n * 2 * np.dot((y_pred_tmp - y_tmp), X_tmp.T)))
    if i % (iterations / 10) == 0:
      print(i, W, err)
  return W

In [24]:
#w_pred_2 = eval_sgd_model(X_st, Y, iterations=2000, qty_in_batch=5, alpha=1e-2)
#w_pred_2

In [25]:
def eval_model_reg2(X, y, iterations, alpha=1e-4, lambda_=1e-8):
  np.random.seed(42)
  W = np.random.randn(X.shape[0])
  n = X.shape[1]
  for i in range(1, iterations+1):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    W -= alpha * (1/n * 2 * np.dot((y_pred - y), X.T) + lambda_ * W) 
    if i % (iterations / 10) == 0:
      print(i, W, err)
  return W

In [26]:
#reg2 = eval_model_reg2(X_st, Y, iterations=500000, alpha=1e-3, lambda_=1e-8)
#reg2

In [27]:
#Y_predict_4 = X_test_st.dot(reg2)
#submissions = pd.concat([test['Id'], pd.Series(Y_predict_4)], axis=1)
#submissions = submissions.rename(columns={0: 'mean_exam_points'})
#submissions.to_csv('Kalmina_reg2.csv',index=None)

In [28]:
def eval_model_reg1(X, y, iterations, alpha=1e-4, lambda_=1e-8):
  np.random.seed(42)
  W = np.random.randn(X.shape[0])
  n = X.shape[1]
  for i in range(1, iterations+1):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    W -= alpha * (1/n * 2 * np.dot((y_pred - y), X.T) + lambda_ * np.sign(W)) 
    if i % (iterations / 10) == 0:
      print(i, W, err)
  return W

In [29]:
#reg1 = eval_model_reg1(X_st, Y, iterations=500000, alpha=1e-3, lambda_=1e-8)
#reg1

In [30]:
# Реализуем класс узла

class Node:
    
    def __init__(self, index, t, true_branch, false_branch):
        self.index = index  # индекс признака, по которому ведется сравнение с порогом в этом узле
        self.t = t  # значение порога
        self.true_branch = true_branch  # поддерево, удовлетворяющее условию в узле
        self.false_branch = false_branch  # поддерево, не удовлетворяющее условию в узле

In [31]:
# И класс терминального узла (листа)

class Leaf:
    
    def __init__(self, data, labels):
        self.data = data
        self.labels = labels
        self.prediction = self.predict()
        
    def predict(self):
        #  найдем значение как среднее по выборке   
        prediction = np.mean(self.labels)
        return prediction

In [32]:
# И класс дерева
class Tree:

  def __init__(self, max_depth=50):
    self.max_depth = max_depth
    self.tree = None

  # Расчёт дисперсии значений
  def dispersion(self, labels):
    return np.std(labels)

  # Расчет качества

  def quality(self, left_labels, right_labels, current_dispersion):

    # доля выбоки, ушедшая в левое поддерево
    p = float(left_labels.shape[0]) / (left_labels.shape[0] + right_labels.shape[0])
    
    return current_dispersion - p * self.dispersion(left_labels) - (1 - p) * self.dispersion(right_labels)

    # Разбиение датасета в узле

  def split(self, data, labels, index, t):
    
    left = np.where(data[:, index] <= t)
    right = np.where(data[:, index] > t)
        
    true_data = data[left]
    false_data = data[right]
    true_labels = labels[left]
    false_labels = labels[right]
        
    return true_data, false_data, true_labels, false_labels

    # Нахождение наилучшего разбиения

  def find_best_split(self, data, labels):
    
    #  обозначим минимальное количество объектов в узле
    min_leaf = 5

    current_dispersion = self.dispersion(labels)

    best_quality = 0
    best_t = None
    best_index = None
    
    n_features = data.shape[1]
    
    for index in range(n_features):
      # будем проверять только уникальные значения признака, исключая повторения
      t_values = np.unique([row[index] for row in data])
      
      for t in t_values:
        true_data, false_data, true_labels, false_labels = self.split(data, labels, index, t)
        #  пропускаем разбиения, в которых в узле остается менее 5 объектов
        if len(true_data) < min_leaf or len(false_data) < min_leaf:
          continue
        
        current_quality = self.quality(true_labels, false_labels, current_dispersion)
        
        #  выбираем порог, на котором получается максимальный прирост качества
        if current_quality > best_quality:
          best_quality, best_t, best_index = current_quality, t, index

    return best_quality, best_t, best_index

    # Построение дерева с помощью рекурсивной функции

  def build_tree(self, data, labels, tree_depth, max_depth):

    quality, t, index = self.find_best_split(data, labels)

    #  Базовый случай - прекращаем рекурсию, когда нет прироста в качества
    if quality == 0:
      return Leaf(data, labels)

    # Базовый случай (2) - прекращаем рекурсию, когда достигнута максимальная глубина дерева
    if tree_depth >= max_depth:
      return Leaf(data, labels)

    # Увеличиваем глубину дерева на 1
    tree_depth += 1

    true_data, false_data, true_labels, false_labels = self.split(data, labels, index, t)

    # Рекурсивно строим два поддерева
    true_branch = self.build_tree(true_data, true_labels, tree_depth, max_depth)
    false_branch = self.build_tree(false_data, false_labels, tree_depth, max_depth)

    # Возвращаем класс узла со всеми поддеревьями, то есть целого дерева
    return Node(index, t, true_branch, false_branch)

  def predict_object(self, obj, node):

    #  Останавливаем рекурсию, если достигли листа
    if isinstance(node, Leaf):
      answer = node.prediction
      return answer

    if obj[node.index] <= node.t:
      return self.predict_object(obj, node.true_branch)
    else:
      return self.predict_object(obj, node.false_branch)

  def predict(self, data):
    
    val = []
    for obj in data:
      prediction = self.predict_object(obj, self.tree)
      val.append(prediction)
    return val

  def fit(self, data, labels):
    self.tree = self.build_tree(data, labels, 0, self.max_depth)
    return self

In [33]:
class GradientBoosting:
  
  def __init__(self, n_trees, max_depth, coefs, eta):
    self.n_trees = n_trees
    self.max_depth = max_depth
    self.coefs = coefs
    self.eta = eta
    self.trees = []

  def bias(self, y, z):
    return (y - z)

  def fit(self, X_train, y_train):
    
    # Деревья будем записывать в список
    trees = []
    
    for i in range(self.n_trees):
        tree = Tree(max_depth=self.max_depth)

        # инициализируем бустинг начальным алгоритмом, возвращающим ноль, 
        # поэтому первый алгоритм просто обучаем на выборке и добавляем в список
        if len(self.trees) == 0:
            # обучаем первое дерево на обучающей выборке
            tree.fit(X_train, y_train)
        else:
            # Получим ответы на текущей композиции
            target = self.predict(X_train)
            
            # алгоритмы начиная со второго обучаем на сдвиг
            bias = self.bias(y_train, target)
            tree.fit(X_train, bias)

        self.trees.append(tree)
        
    return self

  def predict(self, X):
    # Реализуемый алгоритм градиентного бустинга будет инициализироваться нулевыми значениями,
    # поэтому все деревья из списка trees_list уже являются дополнительными и при предсказании прибавляются с шагом eta
    return np.array([sum([self.eta* coef * alg.predict([x])[0] for alg, coef in zip(self.trees, self.coefs)]) for x in X])

In [34]:
def r_2(y_pred, y_true):
  numerator = ((y_true - y_pred) ** 2).sum(axis=0, dtype=np.float64)
  denominator = ((y_true - np.average(y_true)) ** 2).sum(axis=0,
                                                          dtype=np.float64)
  return 1 - (numerator / denominator)

In [35]:
train_data, test_data, train_labels, test_labels = train_test_split(X_st, Y, 
                                                                    test_size = 0.3,
                                                                    random_state = 1)

In [36]:
# Число деревьев в ансамбле
n_trees = 10

# для простоты примем коэффициенты равными 1
coefs = [1] * n_trees

# Максимальная глубина деревьев
max_depth = 6

# Шаг
eta = 0.5

In [37]:
gb = GradientBoosting(n_trees, max_depth, coefs, eta)
gb.fit(train_data, train_labels)
train_answers = gb.predict(train_data)
test_answers = gb.predict(test_data)

In [38]:
r_2(test_answers, test_labels)

0.5889488246130198

In [39]:
r_2(train_answers, train_labels)

0.6907182373351788

In [40]:
gb_final = GradientBoosting(n_trees, max_depth, coefs, eta)
gb_final.fit(X, Y)

In [41]:
test_pred = gb_final.predict(X_test)

In [42]:
test_pred

array([55.94085651, 64.66387139, 48.37453509, ..., 54.73601345,
       65.44632684, 69.74647241])

In [43]:
submissions = pd.concat([test['Id'], pd.Series(test_pred)], axis=1)
submissions = submissions.rename(columns={0: 'mean_exam_points'})

In [44]:
submissions.to_csv('Kalmina_tree_st_last.csv',index=None)